version: '3.7'

services:
  bot:
    image: iteam1337/avvikelseboten
    environment:
      - SLACK_TOKEN
      - DB_USER=iteamadmin
      - DB_PASSWORD=adminadmin1337
      - DB_HOST=postgres
      - DB_DATABASE=avvikelseboten
    networks:
      bot:

  postgres:
    image: postgres:11.5
    volumes:
      - postgres11:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES__USER:-iteamadmin}
      - POSTGRES_PASSWORD=${POSTGRES__PASS:-adminadmin1337}
      - POSTGRES_DB=${POSTGRES__DB:-avvikelseboten}
      - POSTGRES_INITDB_ARGS=--encoding=utf8
    networks:
      bot:
    healthcheck:
      test:
        [
          'CMD',
          'bash',
          '-c',
          "runuser -l postgres -U iteamadmin -c 'pg_isready' || exit 1",
        ]
      interval: 2s
      timeout: 5s
      retries: 3

networks:
  bot:

volumes:
  postgres11:
